Scan password via QR and use label from otpauth when adding TOTP via QR
yogeshpaliyal/KeyPass pull request #92
Opened 2022-02-01 18:29 UTC by eldad

* TOTP QR Scan: parse label from `otpauth` and set account name
* Add "Scan Password" button using QR for regular passwords

Resolves https://github.com/yogeshpaliyal/KeyPass/issues/91

2022-02-01 19:09 UTC, yogeshpaliyal requested changes

2022-02-01 19:09 UTC, yogeshpaliyal commented on app/src/main/res/values/strings.xml
> +    <string name="scan_password">Scan Password</string>
"scan_password" is not translated in "hi" (Hindi) or "zh" (Chinese)

2022-02-01 19:13 UTC, eldad commented on app/src/main/res/values/strings.xml
> +    <string name="scan_password">Scan Password</string>
@yogeshpaliyal I can't speak neither :smile: Shall I just use the result from Google translate?

This is what Google translate gives me:
Hindi पासवर्ड स्कैन करें
Chinese 扫描密码

2022-02-01 19:15 UTC, yogeshpaliyal commented on app/src/main/res/values/strings.xml
> +    <string name="scan_password">Scan Password</string>
@eldad this works great, thanks for these valuable contribution

2022-02-01 19:23 UTC, eldad commented on app/src/main/res/values/strings.xml
> +    <string name="scan_password">Scan Password</string>
Added now

2022-02-02 02:28 UTC, merged

2022-02-02 02:28 UTC, yogeshpaliyal commented
Thanks @eldad  ❤️❤️

2022-02-02 11:35 UTC, eldad commented
Thanks @yogeshpaliyal for the quick feedback and merging! :star_struck: